---
environments:
  '{{ .Environment.Name }}':
helmDefaults:
  wait: false
helmfiles:
  #  - 'regcred/helmfile.yaml'
  #  - 'localstack/helmfile.yaml'
  #  - 'dynamodb/helmfile.yaml'
  #  - 'dynamodb-setup/helmfile.yaml'
  #  - 'mysql/helmfile.yaml'
  - 'refinery/helmfile.yaml'
  - 'read-api-server/helmfile.yaml'
  - 'write-api-server/helmfile.yaml'
  # - 'read-model-updater-local/helmfile.yaml'
