localstack:
  enabled: false
  resources:
    limits:
      cpu: "1"
      memory: "1000Mi"
    requests:
      cpu: "0.5"
      memory: "500Mi"
refinery:
  enabled: true
  image:
    repository: 738575627980.dkr.ecr.ap-northeast-1.amazonaws.com/pah8iobi-ecr-ceer-refinery
    tag: b7e2d69a5004e03710d96921d2fe64e9
    pullPolicy: Always
  resources:
    limits:
      cpu: "1"
      memory: "1000Mi"
    requests:
      cpu: "0.5"
      memory: "500Mi"
regcred:
  enabled: false
  server:
  username:
  password:
ecrCred:
  enabled: false
  server:
  password:
writeApiServer:
  enabled: true
  version: 0.0.1
  image:
    repository: 738575627980.dkr.ecr.ap-northeast-1.amazonaws.com/pah8iobi-ecr-ceer-write-api-server
    tag: 2dc945054dd927c82220541455add4ab30e248ae6ed09b2e52bd9569b2d519ee-amd64
    pullPolicy: Always
  env:
    - name: "RUST_LOG"
      value: "info"
    - name: "RUST_BACKTRACE"
      value: "full"
    - name: "APP__API__HOST"
      value: "0.0.0.0"
    - name: "APP__API__PORT"
      value: "8080"
    - name: "APP__PERSISTENCE__JOURNAL_TABLE_NAME"
      value: "aht9aa1e-journal"
    - name: "APP__PERSISTENCE__JOURNAL_AID_INDEX_NAME"
      value: "aht9aa1e-journal-aid-index"
    - name: "APP__PERSISTENCE__SNAPSHOT_TABLE_NAME"
      value: "aht9aa1e-snapshot"
    - name: "APP__PERSISTENCE__SNAPSHOT_AID_INDEX_NAME"
      value: "aht9aa1e-snapshot-aid-index"
    - name: "APP__PERSISTENCE__JOURNAL_SHARD_COUNT"
      value: "128"
    - name: "APP__AWS__REGION_NAME"
      value: "ap-northeast-1"
  resources:
    limits:
      cpu: "512m"
      memory: "512Mi"
    requests:
      cpu: "256m"
      memory: "256Mi"
  service:
    type: ClusterIP
    port: 8080
    nodePort: 30031
  ingress:
    enabled: true
    alb:
      scheme: internet-facing
      certificateArn: arn:aws:acm:ap-northeast-1:738575627980:certificate/f26b49bf-7740-4e2a-96c6-7594c96dae9c
  replicaCount: 2
  autoscaling:
    enabled: false
  processTimeoutInSec: 10
  hostname: write-ceer-j5ik2o.cwtest.info
  serviceAccount:
    create: false
    name: ceer
  datadog:
    logs:
      enabled: false
readApiServer:
  enabled: true
  version: 0.0.1
  image:
    repository: 738575627980.dkr.ecr.ap-northeast-1.amazonaws.com/pah8iobi-ecr-ceer-read-api-server
    tag: e1ffb9891defb29be6f77f7d63d1d451b3e01b7f31cb763dd60bb2f3a0295eaa-amd64
    pullPolicy: Always
  env:
    - name: "RUST_LOG"
      value: "info"
    - name: "RUST_BACKTRACE"
      value: "full"
    - name: "APP__API__HOST"
      value: "0.0.0.0"
    - name: "APP__API__PORT"
      value: "8080"
    - name: "APP__AWS__REGION_NAME"
      value: "ap-northeast-1"
  resources:
    limits:
      cpu: "512m"
      memory: "512Mi"
    requests:
      cpu: "256m"
      memory: "256Mi"
  service:
    type: ClusterIP
    port: 8080
    nodePort: 30031
  ingress:
    enabled: true
    alb:
      scheme: internet-facing
      certificateArn: arn:aws:acm:ap-northeast-1:738575627980:certificate/f26b49bf-7740-4e2a-96c6-7594c96dae9c
  replicaCount: 2
  autoscaling:
    enabled: false
  processTimeoutInSec: 10
  hostname: read-ceer-j5ik2o.cwtest.info
  serviceAccount:
    create: false
    name: ceer
  datadog:
    logs:
      enabled: false
