[workspace]
resolver = "2"

members = [
    "modules/infrastructure",
    "modules/command/domain",
    "modules/command/processor",
    "modules/command/interface-adaptor-if",
    "modules/command/interface-adaptor-impl",
    "modules/query/interface-adaptor",
    "applications/write-api-server",
    "applications/read-model-updater",
    "applications/read-api-server",
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.44"
async-graphql = "6.0.1"
async-graphql-axum = "6.0.1"
async-trait = "0.1.73"
aws-config = "0.55.1"
aws_lambda_events = { vesrion = "0.10.0", default-features = false }
aws-sdk-dynamodb = "0.28.0"
aws-sdk-dynamodbstreams = "0.28.0"
axum = "0.6.18"
backtrace = "0.3.69"
chrono = "0.4.*"
config = "0.13.3"
derive-new = "0.5.9"
downcast-rs = "1.2.0"
env_logger = "0.10.0"
http = "0.2.4"
hyper = "0.14.26"
itertools = "0.11.0"
lambda_runtime = "0.8.1"
log = "0.4.19"
num = "0.4.1"
once_cell = "1.18.0"
openssl = { version = "0.10.55", features = ["vendored"] }
redis = "0.23.0"
serde = "1.0"
serde_dynamo = "4.2.3"
serde_json = "1.0"
simple_logger = "4.1.0"
sqlx = { version = "0.7.1", default-features = false }
tokio = "1"
tower = "0.4.12"
tower-http = "0.4.3"
tracing = "0.1.37"
tracing-log = "0.1.1"
tracing-subscriber = { version = "0.3.16", default-features = false }
ulid-generator-rs = "0.0.88"

mime = "0.3.16"
refinery = { version = "0.8", features = ["mysql"] }
refinery-core = "0.8"
testcontainers = "0.14.0"