[workspace]
resolver = "2"

members = [
    "modules/infrastructure",
    "modules/command/domain",
    "modules/command/processor",
    "modules/command/interface-adaptor-if",
    "modules/command/interface-adaptor-impl",
    "modules/query/processor",
    "modules/query/interface-adaptor-impl",
    "applications/write-api-server",
    "applications/read-model-updater",
    "applications/read-api-server",
]