env_files = ["./common.env"]

env_scripts = [
'''
#!/bin/sh
echo "--- Using Environments -----------------"
echo "AWS_PROFILE      = $AWS_PROFILE"
echo "AWS_REGION       = $AWS_REGION"
echo "PREFIX           = $PREFIX"
echo "APPLICATION_NAME = $APPLICATION_NAME"
echo "----------------------------------------"
'''
]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_BACKTRACE=1
RUST_TEST_THREADS=1

#[env.TEST]
#script = ['''
#if [[ "1" == "0" ]]; then
#echo ABC
#else
#echo DEF
#fi
#''']

#[tasks.echo]
#workspace = false
#script = ['''
#echo ${TEST}
#''']


[tasks.fmt]
description = "ソースコードをフォーマットします"
workspace = false
install_script = ['''
#!/bin/sh
rustup which rustfmt --toolchain nightly
if [[ $? -ne 0 ]]; then
  rustup install nightly
fi
''']
script = '''
#!/bin/sh
cargo +nightly fmt
'''

[tasks.terraform-create-lock-table]
workspace = false
condition_script = ["./tools/terraform/exisits-terraform-lock-table.sh"]
command = "./tools/terraform/create-lock-table.sh"

[tasks.terraform-create-tf-bucket]
workspace = false
condition_script = ["./tools/terraform/exisits-terraform-lf-bucket.sh"]
command = "./tools/terraform/create-tf-bucket.sh"

[tasks.terraform-init]
workspace = false
command = "./tools/terraform/terraform-init.sh"

[tasks.terraform-plan]
workspace = false
command = "./tools/terraform/terraform-plan.sh"

[tasks.terraform-apply]
workspace = false
command = "./tools/terraform/terraform-apply.sh"
args = ["-auto-approve"]

[tasks.terraform-destroy]
workspace = false
command = "./tools/terraform/terraform-destroy.sh"
args = ["-auto-approve"]

[tasks.update-kubeconfig]
workspace = false
command = "./tools/terraform/update-kubeconfig.sh"

[tasks.export-auth-config-map]
workspace = false
command = "./tools/terraform/export-auth-config-map.sh"

[tasks.apply-auth-config-map]
workspace = false
command = "./tools/terraform/apply-auth-config-map.sh"

# docker-build write-api-server

[tasks.docker-build-write-api-server-amd64]
description = "Docker build for write-api-server on amd64"
workspace = false
command = "./tools/scripts/docker-build-write-api-server.sh"
args = ["amd64"]

[tasks.docker-build-write-api-server-arm64]
workspace = false
command = "./tools/scripts/docker-build-write-api-server.sh"
args = ["arm64"]

[tasks.docker-build-write-api-server]
workspace = false
run_task = { name = ["docker-build-write-api-server-amd64", "docker-build-write-api-server-arm64"], parallel = true }

# docker-build read-api-server

[tasks.docker-build-read-api-server-amd64]
workspace = false
command = "./tools/scripts/docker-build-read-api-server.sh"
args = ["amd64"]

[tasks.docker-build-read-api-server-arm64]
workspace = false
command = "./tools/scripts/docker-build-read-api-server.sh"
args = ["arm64"]

[tasks.docker-build-read-api-server]
workspace = false
run_task = { name = ["docker-build-read-api-server-amd64", "docker-build-read-api-server-arm64"], parallel = true }

# docker-build read-model-updater
[tasks.docker-build-read-model-updater-prod-amd64]
workspace = false
command = "./tools/scripts/docker-build-read-model-updater.sh"

[tasks.docker-build-read-model-updater-local-amd64]
workspace = false
command = "./tools/scripts/docker-build-read-model-updater-local.sh"

# docker-build-all

[tasks.docker-build-prod-all]
workspace = false
run_task = { name = ["docker-build-write-api-server", "docker-build-read-api-server", "docker-build-read-model-updater-prod-amd64"], parallel = true }

[tasks.docker-build-local-all]
workspace = false
run_task = { name = ["docker-build-write-api-server", "docker-build-read-api-server", "docker-build-read-model-updater-local-amd64"], parallel = true }

# docker-compose-up -d

[tasks.docker-compose-up-db]
workspace = false
command = "./tools/scripts/docker-compose-up.sh"
args = ["-d"]

[tasks.docker-compose-up]
workspace = false
command = "./tools/scripts/docker-compose-up.sh"

[tasks.docker-compose-down]
workspace = false
command = "./tools/scripts/docker-compose-down.sh"

# ---------------------------------------------

[tasks.docker-ecr-push-write-api-server]
workspace = false
command = "./tools/scripts/docker-ecr-push-write-api-server.sh"

[tasks.docker-ecr-push-read-api-server]
workspace = false
command = "./tools/scripts/docker-ecr-push-read-api-server.sh"

[tasks.docker-ecr-push-read-model-updater]
workspace = false
command = "./tools/scripts/docker-ecr-push-read-model-updater.sh"

# ecr-push
[tasks.aws-ecr-login]
workspace = false
command = "./tools/scripts/aws-ecr-login.sh"

[tasks.docker-build-ecr-push-write-api-server]
workspace = false
dependencies = ["docker-build-write-api-server", "aws-ecr-login", "docker-ecr-push-write-api-server"]

[tasks.docker-build-ecr-push-read-api-server]
workspace = false
dependencies = ["docker-build-read-api-server", "aws-ecr-login" , "docker-ecr-push-read-api-server"]

[tasks.docker-ecr-build-push]
workspace = false
run_task = { name = ["docker-build-prod-all", "docker-ecr-push-write-api-server", "docker-ecr-push-read-api-server"] }
