environments:
  '{{ .Environment.Name }}':
    values:
      - '../../config/environments/{{ .Environment.Name }}.yaml'

---
releases:
  - name: refinery
    namespace: '{{ .Namespace | default "ceer" }}'
    labels:
      group: refinery
    chart: ../../charts/refinery
    version: 1.0.0
    wait: true
    installedTemplate: '{{ .Values.refinery.enabled }}'
    values:
      - values/settings.yaml.gotmpl