environments:
  '{{ .Environment.Name }}':
    values:
      - '../../config/environments/{{ .Environment.Name }}.yaml'
---
releases:
  - name: read-model-updater-local
    namespace: '{{ .Namespace | default "ceer" }}'
    labels:
      subsystem: read-model-updater-local
      group: read-model-updater-local
    chart: ../../charts/read-model-updater-local
    version: '{{ .Values.readModelUpdater.version }}'
    installedTemplate: '{{ .Values.readModelUpdater.enabled }}'
    values:
      - values/settings.yaml.gotmpl