{{- if .Values.service.enabled }}
{{- $svcType := .Values.service.type }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "write-api-server.fullname" . }}
  labels:
    {{- include "write-api-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if and (eq $svcType "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "write-api-server.selectorLabels" . | nindent 4 }}
{{- end }}