@startuml
'https://plantuml.com/component-diagram

node "Client" as client {
}

node "Write API Server\n(HTTP/Web API)" as writeAPI {
    [Thread Aggregate] as threadAggregate
}

node "Read API Server\n(GraphQL Server)" as readAPI {
    [Query] as query
    [Subscription(未実装)] as subscripton
}

node "Read Model Updater\n(Lambda)" as updater {
}

database "DynamoDB" {
    [Journal(Events)] as journal
    [Snapshot] as snapshot
}

database "RDS(Aurora)" {
  [Thread Read Model] as thread
  [Member Read Model] as member
}

journal -[hidden]- snapshot
thread -[hidden]- member
query -[hidden]- subscripton

writeAPI -d-> threadAggregate

threadAggregate -d-> journal: Put Item
threadAggregate -d-> snapshot: Put/Update Item

journal -r-> updater: DynamoDB\nStreams

updater -r-> thread: SQL Insert/Update/Delete
updater -r-> member: SQL Insert/Update/Delete

thread --> query: SQL Select
member --> query: SQL Select
query -> readAPI

client -d-> writeAPI
client <-r- readAPI

@enduml
